guias/urls.py
from django.urls import path
from . import views
app_name = 'guias'
urlpatterns = [
    path('guia/<int:guia_id>/rutas/', views.rutas_por_guia, name='rutas_por_guia'),
    path('ruta/<int:ruta_id>/', views.detalle_ruta, name='detalle_ruta'),
     path('ruta/<int:ruta_id>/guia/<int:guia_id>/', views.detalle_ruta_con_guia, name='detalle_ruta_con_guia'),
    path('ver_guias/', views.ver_guias, name='ver_guias'),
]

reservacion/urls.py
from django.urls import path
from reservacion import views

app_name = "reservacion"

urlpatterns = [
    path("habitacion_disponible/", views.habitacion_disponible,
         name="habitacion_disponible"),
    path("add_selecion/", views.add_selecion, name="add_selecion"),
    path('mi-reserva/', views.mi_reserva, name='mi-reserva'),
    path('create-payment/', views.create_payment, name='create_payment'),
    path('create-checkout-session/', views.create_checkout_session,
         name='create_checkout_session'),
    path('create-checkout-session-2/', views.create_checkout_session_2,
         name='create_checkout_session_2'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-success-2/', views.payment_success_2, name='payment_success_2'),
    path('payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('mis-reservas/', views.mis_reservas, name='mis_reservas'),
    path('descargar-ticket/<int:reserva_id>/', views.descargar_ticket, name='descargar_ticket'),
    path('descargar-ticket_guia/<int:reserva_id>/', views.descargar_ticket_guia, name='descargar_ticket_guia'),
]

san_andres/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import admin_dashboard


urlpatterns = [
     
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin/', admin.site.urls),
    
    # rutas de usuario auth urls
    path("user/", include("userauths.urls")),
    
    path("", include("alojamiento.urls")),
  
    path("guias/", include("guias.urls")),
    path("reservacion/", include("reservacion.urls")),
    path('reportes/', include('user_dashboard.urls')),
   
    


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/guiasturistico/detalle_ruta.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 my-5 mb-4 px-4">
            <h2 class="fw-bold">CONFIRMAR RESERVACIÓN</h2>
            <div style="font-size: 14px">
                <a href="{% url 'guias:ver_guias' %}" class="text-secondary text-decoration-none text-black-50">Inicio</a>
                <span class="text-secondary"> > </span>
                <a href="{% url 'guias:rutas_por_guia' guia.id %}" class="text-secondary text-decoration-none text-black-50">Actividades</a>
                <span class="text-secondary"> > </span>
                <span class="text-secondary">Confirmar</span>
            </div>
        </div>

        <div class="col-lg-7 col-md-12 px-4" style="margin-top: -1cm;">
            <div class="text-center">
                <h4> Actividad {{ ruta.nombre }}</h4>
            </div>
            <div class="card p-3 shadow-sm rounded">
                <img src="{{ ruta.imagen.url }}" class="card-img-top px-2 fixed-size" alt="Imagen de la ruta" />
                <h5 class="mt-2 text-center">Precio: ${{ ruta.precio }} Por Persona</h5>
                <div class="d-flex justify-content-between small">
                    <div class="d-flex align-items-center"><i class="fa-solid fa-map-pin mr-2"></i>Ruta:</div>
                    <div>{{ ruta.nombre }}</div>
                </div>
                <div class="small d-flex justify-content-between mt-2">
                    <div><i class="fa-solid fa-person-hiking mr-2" style="color: #0953d3;"></i>Capacidad:</div>
                    <div>{{ ruta.capacidad }} personas</div>
                </div>
            </div>
        </div>

        <script src="https://js.stripe.com/v3/"></script>

        <div class="col-lg-5 col-md-12 px-4">
            <div class="card mb-4 border-0 shadow-sm rounded-3">
                <div class="card-body">
                    <form id="booking_form" method="POST">
                        {% csrf_token %}
                        <h6 class="mb-3">Detalles de la reservación</h6>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label class="form-label mb-1">Nombre</label>
                                <input name="name" type="text" class="form-control shadow-none" required>
                            </div>
                            <div class="col-md-6 mb-3" style="margin-top: -5px;">
                                <label class="form-label">Número de teléfono</label>
                                <input name="phonenum" type="tel" class="form-control shadow-none" required maxlength="10" pattern="\d{10}">
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="form-label">Dirección</label>
                                <textarea name="address" class="form-control shadow-none" rows="1" required></textarea>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="form-label">Número de personas</label>
                                <input name="num_person" id="num_person" type="number" class="form-control shadow-none"
                                    min="1" max="{{ ruta.capacidad }}" required onchange="calculateTotal()" oninput="calculateTotal()">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="form-label">Fecha</label>
                                <input name="fecha" type="date" class="form-control shadow-none"
                                    min="{{ fecha_actual|date:'Y-m-d' }}" value="{{ fecha_actual|date:'Y-m-d' }}"
                                    required>
                                <script>
                                    var today = new Date();
                                    today.setDate(today.getDate() + 2); // Añadir 2 días a la fecha actual
                                    var minDate = today.toISOString().split('T')[0];
                                    document.getElementsByName('fecha')[0].setAttribute('min', minDate);
                                </script>
                            </div>
                            <div class="col-12 mb-3">
                                <div id="date-error" class="text-danger mb-3"></div>
                                <h6>Total a pagar: $<span id="totalPrice">0.00</span></h6>
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn w-100 text-white custom-bg shadow-none mb-1 bg-dark"
                                    id="submitBtn">
                                    Pagar Ahora
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="card mt-5 shadow-sm">
        <div class="card-header bg-light">
            <h5 class="fw-bold text-uppercase">Detalle de la Ruta</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <h6 class="fw-bold text-uppercase mb-3">Información del Guía</h6>
                    {% if guia %}
                    <div class="mb-3">
                        <div class="d-flex align-items-center mb-2">
                            <img src="{{ guia.foto.url }}" class="img-fluid rounded-circle me-3" alt="{{ guia.nombre }}" style="object-fit: cover; width: 50px; height: 50px;">
                            <div class="text-dark">
                                <p class="mb-0 ml-2"><strong>Nombre:</strong> {{ guia.nombre }}</p>
                                <p class="mb-0 ml-2"><strong>Email:</strong> <a href="mailto:{{ guia.email }}" class="text-dark">{{ guia.email }}</a></p>
                                <p class="mb-0 ml-2"><strong>Teléfono:</strong> <a href="tel:{{ guia.telefono }}" class="text-dark">{{ guia.telefono }}</a></p>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <p>No hay guía asignado a esta ruta.</p>
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <h6 class="fw-bold text-uppercase mb-3">Descripción de Senderismo</h6>
                    <p>{{ ruta.descripcion }}</p>
                </div>
            </div>
        </div>
    </div>
    
    
    
</div>

<script>
    var precioPorPersona = parseFloat("{{ ruta.precio }}");
    var capacidadMaxima = parseInt("{{ ruta.capacidad }}");

    function calculateTotal() {
        var numPersonas = parseInt(document.getElementById('num_person').value) || 0;
        if (numPersonas > capacidadMaxima) {
            Swal.fire({
                icon: 'error',
                title: 'Excede la capacidad',
                text: `El número máximo de personas permitidas es ${capacidadMaxima}.`
            });
            document.getElementById('num_person').value = capacidadMaxima;
            numPersonas = capacidadMaxima;
        }
        var total = precioPorPersona * numPersonas;
        document.getElementById('totalPrice').innerText = total.toFixed(2);
    }
    document.getElementById("booking_form").addEventListener("submit", function (e) {
        e.preventDefault();
        fetchCheckoutSession();
    });

    async function fetchCheckoutSession() {
        
            
        const response = await fetch("{% url 'reservacion:create_checkout_session_2' %}", {
          
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": "{{ csrf_token }}",
            },
            body: JSON.stringify({
                product_name: "{{ ruta.nombre }}",
                product_image: document.querySelector("img").src,
                amount: parseFloat(precioPorPersona) * 100,  // Convertir a centavos
                fecha: document.querySelector("input[name='fecha']").value,
                num_person: document.querySelector("input[name='num_person']").value,
                name: document.querySelector("input[name='name']").value,
                ruta_id: "{{ ruta.id }}",
            }),
        });

        const session = await response.json();

        if (response.ok) {
            window.location.href = session.url;
        } else {
            console.error(session.error);
        }
    }
</script>

{% endblock %}

templates/guiasturistico/rutas.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
.fixed-size {
  height: 200px;
  width: 100%;
  object-fit: cover;
  padding: 10px; 
  box-sizing: border-box; 
  border-radius: 5px; 
}

.card {
  border: 1px solid #ddd;
  border-radius: 4px;
  margin: 10px;
}

.card-body {
  padding: 15px;
}
</style>

<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="bg-light mt-3 text-center pb-4 bg-registration">
        <div>
          <h1 class="font-weight-bolder text-uppercase text-center text-light py-3">
            Guía turístico: {{ guia.nombre }}
          </h1>
        </div>
        <span class="text-light">
          Rutas ofrecidas: {{ rutas.count }}
        </span>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-lg-12">
      <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for ruta in rutas %}
        <div class="col py-2">
          <div class="card h-100">
            <div class="text-center">
              <h5 class="mt-2 text-center font-weight-bolder bg-success text-light ml-2 mr-2">
                ${{ ruta.precio }} <br />
                Por Persona
              </h5>
            </div>

            <img src="{{ ruta.imagen.url }}" class="card-img-top fixed-size" alt="Imagen de la ruta" />
            <div class="card-body">
              <div>
                <div class="d-flex justify-content-between align-items-center small">
                  <div class="d-flex align-items-center">
                    <i class="fa-solid fa-map-pin mr-2" style="color: #b67402;"></i>Actividad:
                  </div>
                  <div>
                    {{ ruta.nombre }}
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center small mt-2">
                  <div class="d-flex align-items-center">
                    <i class="fa-solid fa-person-hiking mr-2" style="color: #0953d3;"></i>Capacidad:
                  </div>
                  <div>
                    {{ ruta.capacidad }} 
                  </div>
                </div>
               
                <a href="{% url 'guias:detalle_ruta_con_guia' ruta.id guia.id %}" class="mt-2 btn btn-primary btn-sm btn-lg btn-block add-to-selection">
                  <i class="fa-solid fa-calendar-days mr-2" style="color: #1a5dd1;"></i> Reservar
                </a>

                
              </div>
            </div>
          </div>
        </div>

       
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/guiasturistico/ver_guias.html
{% extends 'base.html' %} {% load static %} {% block content %}

<style>
  .card_box {
    overflow: hidden;
    border-radius: 20px;
  }

  .card_box span {
    position: absolute;
    overflow: hidden;
    width: 150px;
    height: 150px;
    top: -25px;
    left: -10px;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1;
  }

  .card_box span::before {
    content: "Más reservado";
    position: absolute;
    width: 150%;
    height: 40px;
    background-image: linear-gradient(45deg, #ff6547 0%, #ffb144 51%, #ff7053 100%);
    transform: rotate(-45deg) translateY(-20px);
    display: flex;
    align-items: center;
    justify-content: center;
    color: #fff;
    font-weight: 600;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.23);
  }

  .card_box span::after {
    content: "";
    position: absolute;
    width: 10px;
    bottom: 0;
    left: 0;
    height: 10px;
    z-index: -1;
    box-shadow: 140px -140px #cc3f47;
    background-image: linear-gradient(45deg, #ff512f 0%, #f09819 51%, #ff512f 100%);
  }
</style>

<div class="my-5 px-4">
  <h2 class="fw-bold h-font text-center">Guías Turísticos</h2>
  <div class="h-line bg-dark"></div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3 col-md-12 mb-lg-0 mb-4 ps-4">
      <!-- Formulario de filtro -->
      <div class="container-fluid position-relative nav-bar p-0">
        <nav class="navbar navbar-expand-lg bg-light navbar-light shadow-lg">
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarfiltro">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-between px-3" id="navbarfiltro">
            <div class="navbar-nav mr-auto py-0">
              <form method="GET" action="{% url 'guias:ver_guias' %}" class="w-100">
                <h4 class="mt-2">Buscar por</h4>

                <!-- Filtro por precio máximo de las rutas asociadas -->
                <div class="border bg-light p-3 rounded mb-3">
                  <h5 class="mb-3" style="font-size: 18px;">Precio máximo de las actividades</h5>
                  <input type="number" name="precio_max" class="form-control" value="{{ request.GET.precio_max }}" min="0" step="0.01" oninput="validatePrice(this)" onkeydown="preventInvalidInput(event)" />
                </div>
                <script>
                  function validatePrice(input) {
                    if (input.value < 0) {
                      input.value = 0;
                    }
                  }

                  function validateInteger(input) {
                    if (input.value < 1) {
                      input.value = 1;
                    } else {
                      input.value = Math.floor(input.value);
                    }
                  }

                  function preventInvalidInput(event) {
                    const invalidChars = ["-", "e", "+"];
                    if (invalidChars.includes(event.key)) {
                      event.preventDefault();
                    }
                  }

                  document.querySelectorAll('input[type="number"]').forEach((input) => {
                    input.addEventListener("input", (event) => {
                      if (input.min !== "" && parseFloat(input.value) < parseFloat(input.min)) {
                        input.value = input.min;
                      }
                      if (input.name === "num_camas" || input.name === "capacidad") {
                        input.value = Math.floor(input.value);
                      }
                    });
                  });
                </script>
                <!-- Filtro por guía con más rutas asociadas -->
                <div class="border bg-light p-3 rounded mb-3">
                  <h5 class="mb-3" style="font-size: 18px;">Guía con más actividades</h5>
                  <input type="checkbox" id="guia_mas_rutas" name="guia_mas_rutas" value="1" style="margin-left: -5px;" class="form-check-input" {% if request.GET.guia_mas_rutas %}checked{% endif %} />
                  <label class="form-check-label ml-3" for="guia_mas_rutas">Mostrar actividades del guía</label>
                </div>

                <!-- Filtro por ruta más reservada -->
                <div class="border bg-light p-3 rounded mb-3">
                  <h5 class="mb-3" style="font-size: 18px;">Ruta más reservada</h5>
                  <input type="checkbox" id="ruta_mas_reservada" name="ruta_mas_reservada" value="1" style="margin-left: -5px;" class="form-check-input" {% if request.GET.ruta_mas_reservada %}checked{% endif %} />
                  <label class="form-check-label ml-3" for="ruta_mas_reservada">Mostrar ruta más reservada</label>
                </div>

                <!-- Filtro por guía más reservado -->
                <div class="border bg-light p-3 rounded mb-3">
                  <h5 class="mb-3" style="font-size: 18px;">Guía más reservado</h5>
                  <input type="checkbox" id="guia_mas_reservado" name="guia_mas_reservado" value="1" style="margin-left: -5px;" class="form-check-input" {% if request.GET.guia_mas_reservado %}checked{% endif %} />
                  <label class="form-check-label ml-3" for="guia_mas_reservado">Mostrar guía más reservado</label>
                </div>

                <!-- Botón de filtrar -->
                <button type="submit" class="btn btn-primary w-100">Aplicar filtros</button>
                <br />
                <br />
              </form>
            </div>
          </div>
        </nav>
      </div>
    </div>

    <div class="col-lg-9 col-md-12 px-4">
      {% if messages %} {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
      {% endfor %} {% endif %} {% if guiaturisticos %} {% for guia in guiaturisticos %}
      <div class="card mb-4 border-0 shadow">
        <div class="row g-0 p-3 align-items-center">
          <div class="col-md-5 mb-lg-0 mb-md-0 mb-3">
            <div class="card_box">
              {% if mostrar_cinta and guia.es_mas_reservado %}
              <span></span>
              {% endif %}
              <img src="{{ guia.foto.url }}" class="card-img rounded" style="height: 210px; object-fit: cover;" alt="..." />
            </div>
          </div>
          <div class="col-md-5 px-lg-3 px-md-3 px-0">
            <h5 class="mb-3">{{ guia.nombre|upper }}</h5>
            <div class="facilities mb-1">
              <span class="badge rounded-pill bg-light text-wrap me-1 mb-1 text-black-50">
                <i class="fa fa-envelope mr-2" style="color: #5abf60;"></i>
                {{ guia.email }}
              </span>
              <span class="badge rounded-pill bg-light text-wrap text-justify me-1 mb-1 text-black-50"> <i class="fa fa-phone mr-2" style="color: #5abf60;"></i> {{ guia.telefono }} </span>
            </div>
            <div class="rutas mt-3">
              <h6>Rutas ofrecidas:</h6>
              {% for ruta in guia.rutas.all|slice:":2" %}
              <span class="badge rounded-pill bg-light text-dark text-wrap me-1 mb-1">
                {{ ruta.nombre }} - ${{ ruta.precio }}
              </span>
              {% endfor %}
            </div>
          </div>
          <div class="col-md-2 mt-lg-0 mt-md-0 mt-4 text-center">
            <a href="{% url 'guias:rutas_por_guia' guia.id %}" class="btn btn-sm w-100 text-white shadow-none mb-2" style="background-color: #7ab730;">Ver todas las rutas</a>
          </div>
        </div>
      </div>
      {% endfor %} {% endif %}
    </div>
  </div>
</div>

<div>
  {% include 'paginator.html' with entity=guiaturisticos paginator=paginator%}
</div>

{% endblock %}