alojamiento/urls.py
from django.urls import path
from alojamiento import views

app_name = "alojamiento"

urlpatterns = [
    path("", views.index, name="index"),
    path('webhook/', views.webhook, name='webhook'),
    

    path("detalle/<int:pk>", views.alojamiento_detalle, name="alojamiento_detalle"),
    path("detalle/<int:pk>/tipos-alojamiento/<int:ta_pk>/", views.tipos_alojamiento_detalle, name="tipos_alojamiento_detalle"),
    path("ver_alojamiento_detalle/", views.ver_alojamientos_detalle, name="ver_alojamientos_detalle"),
]

guias/urls.py
from django.urls import path
from . import views
app_name = 'guias'
urlpatterns = [
    path('guia/<int:guia_id>/rutas/', views.rutas_por_guia, name='rutas_por_guia'),
    path('ruta/<int:ruta_id>/', views.detalle_ruta, name='detalle_ruta'),
     path('ruta/<int:ruta_id>/guia/<int:guia_id>/', views.detalle_ruta_con_guia, name='detalle_ruta_con_guia'),
    path('ver_guias/', views.ver_guias, name='ver_guias'),
]

reservacion/urls.py
from django.urls import path
from reservacion import views

app_name = "reservacion"

urlpatterns = [
    path("habitacion_disponible/", views.habitacion_disponible,
         name="habitacion_disponible"),
    path("add_selecion/", views.add_selecion, name="add_selecion"),
    path('mi-reserva/', views.mi_reserva, name='mi-reserva'),
    path('create-payment/', views.create_payment, name='create_payment'),
    path('create-checkout-session/', views.create_checkout_session,
         name='create_checkout_session'),
    path('create-checkout-session-2/', views.create_checkout_session_2,
         name='create_checkout_session_2'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-success-2/', views.payment_success_2, name='payment_success_2'),
    path('payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('mis-reservas/', views.mis_reservas, name='mis_reservas'),
    path('descargar-ticket/<int:reserva_id>/', views.descargar_ticket, name='descargar_ticket'),
    path('descargar-ticket_guia/<int:reserva_id>/', views.descargar_ticket_guia, name='descargar_ticket_guia'),
]

san_andres/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import admin_dashboard


urlpatterns = [
     
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin/', admin.site.urls),
    
    # rutas de usuario auth urls
    path("user/", include("userauths.urls")),
    
    path("", include("alojamiento.urls")),
  
    path("guias/", include("guias.urls")),
    path("reservacion/", include("reservacion.urls")),
    path('reportes/', include('user_dashboard.urls')),
   
    


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from userauths import views
from userauths.views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView
app_name = 'userauths'

urlpatterns = [
    path("sign-up", views.RegistrarVista, name="sign-up"),
    path("sign-in", views.LoginVista, name="sign-in"),
    path("sign-out", views.Cerrar_Sesion, name="sign-out"),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>San Andres</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   

    <!-- Favicon -->

    <link rel="icon" href="{% static 'img/viajar.png' %}" type="image/x-icon">
   
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
   
    <!-- alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <!-- Customized Bootstrap Stylesheet -->
    
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap5.css"/>
 
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.bundle.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap5.js"></script>

</head>

<body>
    <!-- Navbar Start -->
    
    
    <div class="container-fluid position-relative nav-bar p-0">
        <div class="container-fluid position-relative p-0" style="z-index: 9;">
            <nav class="navbar navbar-expand-lg bg-light navbar-light shadow-lg py-3 py-lg-0 pl-3 pl-lg-5">
                <a href="/" class="navbar-brand">
                    <h1 class="m-0 text-primary"><span class="text-dark">SAN </span>ANDRES</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="/" class="nav-item nav-link active">Inicio</a>
                        <a href="{% url 'alojamiento:ver_alojamientos_detalle' %}" class="nav-item nav-link">Alojamiento</a>
                        <a href="{% url 'guias:ver_guias' %}" class="nav-item nav-link">Guías Turísticos</a>
                        
                        {% if user.is_authenticated %}
                            <a href="{% url 'reservacion:mis_reservas' %}" class="nav-item nav-link">Mis reservas</a>
                        {% endif %}
                        <!-- <a href="contact.html" class="nav-item nav-link">Contáctanos</a> -->
                    </div>
                    <div class="navbar-nav ml-2">
                        {% if user.is_authenticated %}
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary shadow-none dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-user"></i> {{ user.full_name }}
                                </button>
                                <div class="dropdown-menu dropdown-menu-right">
                                  
                                    <a class="dropdown-item" href="{% url 'reservacion:mis_reservas' %}">Mis Reservas</a>
                                    <a class="dropdown-item" href="{% url 'userauths:sign-out' %}">Salir</a>
                                </div>
                            </div>
                        {% else %}
                        <div class="d-flex flex-wrap">
                            <a href="{% url 'userauths:sign-in' %}" class="btn btn-primary shadow-none me-2 mb-2" style="margin-right: 10px;">Iniciar Sesión</a>
                            <a href="{% url 'userauths:sign-up' %}" class="btn btn-primary shadow-none mb-2">Registrarse</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </div>
    </div>
    
    
    <!-- Navbar End -->
    {% block slider_content %}{% endblock slider_content %}


    {% block content %} {% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 py-4 px-sm-3 px-lg-5" style="margin-top: 90px;">
        <div class="row">
            <div class="col-lg-4 col-md-6 mb-4">
                <a href="" class="navbar-brand">
                    <h1 class="text-primary"><span class="text-white">SAN</span>ANDRES</h1>
                </a>
                <p>Un destino majestuoso en Ecuador que ofrece paisajes
                     naturales impresionantes y una rica cultura indígena, 
                     ideal para aventuras y experiencias únicas.
                    </p>
            </div>
            <div class="col-lg-4 col-md-6 mb-4 ">
                <h5 class="text-white text-uppercase mb-3" style="letter-spacing: 5px;">Servicios</h5>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white-50 mb-2" href="/"><i class="fa fa-angle-right mr-2"></i>Inicio</a>
                    <a class="text-white-50 mb-2" href="{% url 'alojamiento:ver_alojamientos_detalle' %}"><i class="fa fa-angle-right mr-2"></i>Alojamiento</a>
                    <a class="text-white-50 mb-2" href="{% url 'guias:ver_guias' %}"><i class="fa fa-angle-right mr-2"></i>Guías Locales</a>
                    <a class="text-white-50 mb-2" ><i class="fa fa-angle-right mr-2"></i>Asistente virtual</a>
                </div>
            </div>
           
            <div class="col-lg-4 col-md-6 mb-4">
                <h5 class="text-white text-uppercase mb-3" style="letter-spacing: 5px;">Contáctanos</h5>
                <p><i class="fa fa-map-marker-alt mr-2"></i>San Andrés, Chimborazo</p>
                <p><i class="fa fa-phone-alt mr-2"></i> 32904472</p>
                <p><i class="fa fa-envelope mr-2"></i> Sanandesguanochimborazo@yahoo.es</p>
            </div>
        </div>
        <p class="m-0 text-center">© 2024 Desarrollado por Stalyn. Todos los derechos reservados.</p>
    </div>
    </div>
    
    <!-- Footer End -->

    <script>
        const Toast = Swal.mixin({
            toast: true,
            position: "top-start",
            showConfirmButton: false,
            timer: 1300,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            },
        });
    </script>
    {% for message in messages %}
    <script>

        Toast.fire({
            icon: "{{ message.tags }}",
            title: "{{ message }}"
        });
    </script>
    {% endfor %}
    
    <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
    <df-messenger
    intent="WELCOME"
    chat-title="VoyAventura"
    agent-id="01e9cacf-8a7a-4756-ab72-fa219a36255c"
    language-code="es"
    chat-icon="/static/img/voyaventura.png"
   
    wait-open ="true"
    ></df-messenger>
   
    <!-- JavaScript Libraries -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="/static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="/static/js/main.js"></script>
    <script src="/static/js/custom.js"></script>
   
   
</body>

</html>

templates/login.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>Login</h1>
{% endblock %}
{% block login-status %}
{% endblock %}
{% block main-content %}
    {% if form.errors %}
        <p class="notMatched">Username and password didn't match. Please Try Again.</p>
    {% endif %}
    {% if next %}
        {% if user.is_authenticated %}
            <p>You don't have access to view this page.</p>
        {% else %}
            <p>You must login to view this page.</p>
        {% endif %}
    {% endif %}
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <div class="form-group col-auto">
                <label for="{{ form.username.id_for_label }}">Username</label>{{ form.username }}
            </div>
            <div class="form-group col-auto">
                <label for="{{ form.password.id_for_label }}">Password</label>{{ form.password }}
            </div>
        </div>
        <input type="submit" value="Login"/>
        <input type="hidden" name="next" value="{{ next }}"/>
    </form>

    {# Assumes you setup the password_reset view in your URLconf #}
    <p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

templates/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}