alojamiento/urls.py
from django.urls import path
from alojamiento import views

app_name = "alojamiento"

urlpatterns = [
    path("", views.index, name="index"),
    path('webhook/', views.webhook, name='webhook'),
    

    path("detalle/<int:pk>", views.alojamiento_detalle, name="alojamiento_detalle"),
    path("detalle/<int:pk>/tipos-alojamiento/<int:ta_pk>/", views.tipos_alojamiento_detalle, name="tipos_alojamiento_detalle"),
    path("ver_alojamiento_detalle/", views.ver_alojamientos_detalle, name="ver_alojamientos_detalle"),
]

guias/urls.py
from django.urls import path
from . import views
app_name = 'guias'
urlpatterns = [
    path('guia/<int:guia_id>/rutas/', views.rutas_por_guia, name='rutas_por_guia'),
    path('ruta/<int:ruta_id>/', views.detalle_ruta, name='detalle_ruta'),
     path('ruta/<int:ruta_id>/guia/<int:guia_id>/', views.detalle_ruta_con_guia, name='detalle_ruta_con_guia'),
    path('ver_guias/', views.ver_guias, name='ver_guias'),
]

reservacion/urls.py
from django.urls import path
from reservacion import views

app_name = "reservacion"

urlpatterns = [
    path("habitacion_disponible/", views.habitacion_disponible,
         name="habitacion_disponible"),
    path("add_selecion/", views.add_selecion, name="add_selecion"),
    path('mi-reserva/', views.mi_reserva, name='mi-reserva'),
    path('create-payment/', views.create_payment, name='create_payment'),
    path('create-checkout-session/', views.create_checkout_session,
         name='create_checkout_session'),
    path('create-checkout-session-2/', views.create_checkout_session_2,
         name='create_checkout_session_2'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-success-2/', views.payment_success_2, name='payment_success_2'),
    path('payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('mis-reservas/', views.mis_reservas, name='mis_reservas'),
    path('descargar-ticket/<int:reserva_id>/', views.descargar_ticket, name='descargar_ticket'),
    path('descargar-ticket_guia/<int:reserva_id>/', views.descargar_ticket_guia, name='descargar_ticket_guia'),
]

san_andres/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import admin_dashboard


urlpatterns = [
     
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin/', admin.site.urls),
    
    # rutas de usuario auth urls
    path("user/", include("userauths.urls")),
    
    path("", include("alojamiento.urls")),
  
    path("guias/", include("guias.urls")),
    path("reservacion/", include("reservacion.urls")),
    path('reportes/', include('user_dashboard.urls')),
   
    


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alojamiento/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Alojamiento

User = get_user_model()

class AlojamientoAdminForm(forms.ModelForm):
    class Meta:
        model = Alojamiento
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].queryset = User.objects.filter(is_staff=True)

alojamiento/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from alojamiento.models import Alojamiento,TipoAlojamiento,GaleriaAlojamiento ,Habitacion, Reservacion
from guias.models import GuiaTuristico, Ruta
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Min, Max, Count
from django.contrib import messages
from django.urls import reverse
from django.core.paginator import Paginator
from userauths.models import MensajeUsuario

from san_andres import settings
import openai

def index(request):
    alojamiento = Alojamiento.objects.filter(estado="Aprobado")[:3]
    guiaturisticos = GuiaTuristico.objects.filter(
    Q(estado="Aprobado") | Q(estado="Disponible")
    )
    
    context = {
        "alojamiento": alojamiento,
        "guiaturisticos": guiaturisticos,  # Pasamos los guías turísticos al contexto
    }
    return render(request, "alojamiento/alojamiento.html", context)


def alojamiento_detalle(request, pk):
    alojamiento = Alojamiento.objects.get(estado="Aprobado", pk=pk)
    context = {
        "alojamiento": alojamiento,
    }
    return render(request, "alojamiento/alojamiento_detalle.html", context)


    
@login_required(login_url="userauths:sign-in")
def tipos_alojamiento_detalle(request, pk, ta_pk):
    alojamiento = Alojamiento.objects.get(estado="Aprobado", pk=pk)
    tipos_alojamiento = TipoAlojamiento.objects.get(alojamiento=alojamiento, pk=ta_pk)
    habitaciones = Habitacion.objects.filter(alojamiento_tipo=tipos_alojamiento, disponible=True)
    
    id= request.GET.get("alojamiento-id")
    fecha_ingreso = request.GET.get("fecha_ingreso")
    fecha_salida = request.GET.get("fecha_salida")
    num_adultos = request.GET.get("num_adultos")
    num_ninos = request.GET.get("num_ninos")

    

    context = {
        "alojamiento": alojamiento,
        "tipos_alojamiento": tipos_alojamiento,
        "habitaciones": habitaciones,
        "fecha_ingreso": fecha_ingreso,
        "fecha_salida": fecha_salida,
        "num_adultos": num_adultos,
        "num_ninos": num_ninos,
    }
    return render(request, "alojamiento/tipos_alojamiento_detalle.html", context)

def ver_alojamientos_detalle(request):
    alojamientos = Alojamiento.objects.filter(estado="Aprobado")
    applied_filters = False
    page  = request.GET.get('page',1)

    # Obtener parámetros de filtro
    precio_max = request.GET.get('precio_max')
    num_camas = request.GET.get('num_camas')
    capacidad = request.GET.get('capacidad')
    mas_reservas = request.GET.get('mas_reservas')

    # Aplicar filtros
    if precio_max and precio_max.strip():
        alojamientos = alojamientos.filter(tipoalojamiento__precio__lte=float(precio_max))
        applied_filters = True

    if num_camas and num_camas.strip():
        alojamientos = alojamientos.filter(tipoalojamiento__numero_camas__gte=int(num_camas))
        applied_filters = True

    if capacidad and capacidad.strip():
        alojamientos = alojamientos.filter(tipoalojamiento__capacidad__gte=int(capacidad))
        applied_filters = True

    # Ordenar por más reservas si está activado el filtro
    if mas_reservas:
        alojamientos = alojamientos.annotate(num_reservas=Count('reservacion')).order_by('-num_reservas')
        applied_filters = True

    # Anotar campos adicionales
    alojamientos = alojamientos.annotate(
        precio_min=Min('tipoalojamiento__precio'),
        precio_max=Max('tipoalojamiento__precio'),
        max_capacidad=Max('tipoalojamiento__capacidad'),
        max_camas=Max('tipoalojamiento__numero_camas'),
        num_reservas=Count('reservacion')
    ).distinct()

    # Verificar si no hay resultados después de aplicar filtros
    if applied_filters and not alojamientos.exists():
        messages.warning(request, "No se encontraron resultados para los filtros seleccionados.")
        return redirect(reverse('alojamiento:ver_alojamientos_detalle'))
    
    # paginado 
    try:
         paginator = Paginator(alojamientos,3)
         alojamientos = paginator.page(page)
    except:
         raise Http404
    context = {
        "alojamientos": alojamientos,
        "paginator":paginator,
    }

    return render(request, "alojamiento/ver_alojamientos.html", context)




@csrf_exempt
def webhook(request):
    try:
        body_unicode = request.body.decode('utf-8')
        body = json.loads(body_unicode)

        action = body['queryResult'].get('action')
        event = body['queryResult'].get('queryText')  # El evento se recibe en queryText cuando se activa por un chip
        parameters = body['queryResult']['parameters']

        # Punto de interrupción para inspeccionar la acción y el evento
        print(f"Action: {action}, Event: {event}")
        
        
        if action == 'input.welcome':
            return bienvenida(request) 
        elif action == 'get_alojamiento':
            return get_alojamiento(request)
        elif action == 'info_alojamiento' or event == 'detalle_alojamiento':
            nombre_alojamiento = parameters.get('alojamiento')
            print(f"Nombre del Alojamiento consultado: {nombre_alojamiento}")
            return get_info_alojamiento(request, nombre_alojamiento)
        elif action == 'get_guias':
            return get_guias(request)
        elif action == 'get_detalles_guias'or event == 'detalle_guia' :
            nombre_guia = parameters.get('nombre_guia')
            print(f"Nombre del Guía consultado: {nombre_guia}")
            return get_info_guia(request, nombre_guia)
        elif action == 'responder_pregunta' :
             return responder_pregunta_especifica(request, body)
        elif action == 'capturar_mensaje_usuario':
            return capturar_mensaje_usuario(request, parameters)
        
        elif action == 'capturar_precio':
            return capturar_precio(request, parameters)
       

        elif action == 'mostrar_menu':
            return mostrar_menu(request)
        else:
            return JsonResponse({'fulfillmentText': 'No se pudo procesar la acción solicitada.'})
    except Exception as e:
        print(f"Error en webhook: {str(e)}")
        return JsonResponse({'fulfillmentText': 'Ocurrió un error procesando la solicitud.'})
    # https://voyaventura-san-andres.up.railway.app/webhook/

import time
from functools import wraps

def medir_tiempo(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        inicio = time.time()
        resultado = func(*args, **kwargs)
        fin = time.time()
        tiempo_transcurrido = fin - inicio
        print(f"Tiempo de {func.__name__}: {tiempo_transcurrido} segundos")
        return resultado
    return wrapper

# @medir_tiempo
# def get_info_alojamiento(request, nombre_alojamiento):
#     try:
#         alojamiento = Alojamiento.objects.filter(
#             Q(nombre__icontains=nombre_alojamiento) & Q(estado="Aprobado")
#         ).first()
        
#         if alojamiento:
#             print(f"Alojamiento encontrado: {alojamiento.nombre}")
#             response = {
#                 "fulfillmentMessages": [
#                     {
#                         "payload": {
#                             "richContent": [
#                                 [
#                                     {
#                                         "type": "info",
#                                         "title": alojamiento.nombre,
#                                         "subtitle": f"Dirección: {alojamiento.direccion}",
#                                         "image": {
#                                             "src": {
#                                                 "rawUrl": request.build_absolute_uri(alojamiento.imagen.url)
#                                             }
#                                         },
#                                         "actionLink": f"{settings.DOMAIN}/detalle/{alojamiento.id}"
#                                     }
#                                 ]
#                             ]
#                         }
#                     },
#                     {
#                         "text": {
#                             "text": [
#                                 f"Teléfono: {alojamiento.celular}",
#                                 f"Descripción: {alojamiento.descripcion}"
#                             ]
#                         }
#                     }
#                 ]
#             }
#         else:
#             print(f"No se encontró alojamiento para: {nombre_alojamiento}")
#             response = {
#                 "fulfillmentMessages": [
#                     {
#                         "text": {
#                             "text": ["Lo siento, no pude encontrar información sobre ese alojamiento."]
#                         }
#                     }
#                 ]
#             }
#     except Exception as e:
#         print(f"Error en get_info_alojamiento: {str(e)}")
#         response = {
#             "fulfillmentMessages": [
#                 {
#                     "text": {
#                         "text": ["Ocurrió un error al buscar la información del alojamiento."]
#                     }
#                 }
#             ]
#         }

    
    
#     return JsonResponse(response)


def get_info_alojamiento(request, nombre_alojamiento):
    try:
        alojamiento = Alojamiento.objects.filter(
            Q(nombre__icontains=nombre_alojamiento) & Q(estado="Aprobado")
        ).first()
        
        if alojamiento:
            print(f"Alojamiento encontrado: {alojamiento.nombre}")
            response = {
                "fulfillmentMessages": [
                    {
                        "payload": {
                            "richContent": [
                                [
                                    {
                                        "type": "info",

templates/alojamiento/alojamiento.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- portada carousel -->
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />



<div class="container-fluid px-lg-4 mt-4" >
    <div class="swiper swiper-container" style="margin-top: 1cm;">
        <div class="swiper-wrapper">
           
             
                    <div class="swiper-slide">
                        <img src="{% static 'img/carousel-v2.jpg' %}" class="w-100 d-block" style="height: 470px; object-fit: cover;">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 900px;">
                                <h4 class="text-white text-uppercase mb-md-3">GAD PARROQUIAL DE SAN ANDRES</h4>
                                <h1 class="display-3 text-white mb-md-4">Alojamiento Único e  Inolvidable</h1>
                            </div>
                            
                        </div>
                    </div>
                    
                    <div class="swiper-slide">
                        <img src="{% static 'img/carousel-v1.jpg' %}" class="w-100 d-block" style="height: 470px; object-fit: cover;">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 900px;">
                                <h4 class="text-white text-uppercase mb-md-3"> GAD PARROQUIAL DE SAN ANDRES</h4>
                                <h1 class="display-3 text-white mb-md-4">Guías Expertos  Viajes Memorables</h1>
                            </div>
                        </div>
                    </div>
            

            
        </div>
    </div>
</div>


 
<!-- portada carousel fin -->




<!-- Service Start -->
<div class="container-fluid py-5">
    <div class="container pt-5 pb-3">
        <div class="text-center mb-3 pb-3">
            <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Servicios</h6>
            <h1>Alojamiento & Guías Turísticos</h1>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="service-item bg-white text-center mb-2 py-5 px-4">
                    <i class="fa fa-2x fa-route mx-auto mb-4"></i>
                    <h5 class="mb-2"> Guía Turísticos</h5>
                    <p class="m-0">
                        Descubre nuestra ciudad encantadora con guías expertos. Monumentos históricos, gastronomía local, paisajes deslumbrantes. 
                </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="service-item bg-white text-center mb-2 py-5 px-4">
                    <i class="fa fa-2x fa-robot mx-auto mb-4"></i>
                    <h5 class="mb-2">Asistente Virtual</h5>
                    <p class="m-0">
                        ¿Tienes preguntas? Utiliza nuestro asistente virtual. Respuestas rápidas y precisas a tus dudas. Asistencia confiable cuando la necesites.
                    </p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="service-item bg-white text-center mb-2 py-5 px-4">
                    <i class="fa fa-2x fa-hotel mx-auto mb-4"></i>
                    <h5 class="mb-2">Alojamiento</h5>
                    <p class="m-0">
                        Descubre alojamientos disponibles para tu viaje. Variedad de opciones, detalles precisos. Reserva tu hospedaje ideal aquí.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Service End -->


<!-- Packages Start -->
<div class="container-fluid py-2">
    <div class="container pt-2 pb-3">
        <div class="text-center mb-3 pb-3">
            <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Alojamiento</h6>
            <h1>Tu Perfecto Lugar</h1>
        </div>
        <div class="row">
            {% for a in alojamiento %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card border-0 shadow" style="max-width: 40060px; margin:auto;">
                    <div class="m-2">
                        <img class="img-fluid w-100" src="{{ a.imagen.url }}" style='height: 220px; object-fit: cover;'>
                    </div>
                    <div class="p-4">
                        <div class="mb-3">
                            <small class="m-0">Dirección</small>
                            <div class="d-flex align-items-center">
                                <i class="fa fa-map-marker-alt text-primary mr-2"></i>
                                <span>{{ a.direccion }}</span>
                            </div>
                            <small class="m-0">Teléfono</small>
                            <div class="d-flex align-items-center">
                                <i class="fa fa-phone text-primary mr-2"></i>
                                <span>{{ a.celular }}</span>
                            </div>
                        </div>
                        <a class="h5 text-decoration-none" href="{% url 'alojamiento:alojamiento_detalle' a.pk %}">{{ a.nombre|upper }}</a>
                        <div class="border-top mt-4 pt-4">
                            <div class="d-flex justify-content-between">
                                <h6 class="m-0" href="#"><i class="fa fa-bed mr-2"></i> <small>VER HABITACIONES</small></h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                        
            {% endfor %}
        </div>
        <div class="col-lg-12  text-center mt-5">
            <a href="{% url 'alojamiento:ver_alojamientos_detalle' %}" class="btn btn-sm btn-outline-dark rounded-0 fw-bold shadow-none">Mas Alojamientos</a>
        </div>
        </div>
    </div>
</div>


<div class="slide-container swiper">
    <div class="text-center mb-3 pb-3">
        <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Guías Turísticos</h6>
        <h1>Lugares Por Explorar</h1>
    </div>
    <div class="slide-content">
        <div class="card-wrapper swiper-wrapper">
            {% for guia in guiaturisticos %}
                {% with ruta=guia.rutas.first %}
                <div class="card swiper-slide">
                    <div class="image-content">
                        <span class="overlay" style="background-image: url('{{ ruta.imagen.url  }}');"></span>
                        <div class="card-image">
                            <img class="card-img" src="{{ guia.foto.url}}" alt="Imagen de la ruta">
                        </div>
                    </div>
                    <div class="card-content" style=" margin-left: -1.1cm;">
                        <h2 class="name mt-5" style=" margin-right: -1cm;">{{ guia.nombre }}</h2>
                        <div class="mb-3">
                            <small class="m-0">Correo</small>
                            <div class="d-flex align-items-center">
                               
                                <i class="fa-solid fa-envelope text-primary mr-2"></i>
                                <span>{{ guia.email }}</span>
                            </div>
                            <small class="m-0">Teléfono</small>
                            <div class="d-flex align-items-center">
                                <i class="fa fa-phone text-primary mr-2"></i>
                                <span>{{ guia.telefono }}</span>
                            </div>
                        </div>
                       
                        <button class="button">
                            <a class="text-light"  href="{% url 'guias:rutas_por_guia' guia.pk %}">VER MAS ACTIVIDADES</a>
                        </button>
                    </div>
                </div>
                {% endwith %}
            {% endfor %}
        </div>
        <div class="col-lg-12  text-center mt-5">
            <a href="{% url 'guias:ver_guias' %}" class="btn btn-sm btn-outline-dark rounded-0 fw-bold shadow-none">Mas guías turísticos</a>
        </div>
    </div>
    <div class="swiper-button-next swiper-navBtn"></div>
    <div class="swiper-button-prev swiper-navBtn"></div>
    <div class="swiper-pagination"></div>
</div>



<script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>

<style>
.slide-container{
  max-width: 1120px;
  width: 100%;
  padding: 40px 0;
}
.slide-content{
  margin: 0 40px;
  overflow: hidden;
  border-radius: 25px;
}
.card{
  border-radius: 25px;
  background-color: #FFF;
}
.image-content,
.card-content{
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 10px 14px;
}
.image-content{
  position: relative;
  row-gap: 5px;
  padding: 25px 0;
}
.overlay{
  position: absolute;
  left: 0;
  top: 0;
  height: 100%;
  width: 100%;
  background-size: cover;
  background-position: center;
  border-radius: 25px 25px 0 25px;
}
.overlay::before,
.overlay::after{
  content: '';
  position: absolute;
  right: 0;
  bottom: -40px;
  height: 40px;
  width: 40px;
  background-color: #fafafa;
}
.overlay::after{
  border-radius: 0 25px 0 0;
  background-color: #FFF;
}
.card-image{
  position: relative;
  height: 150px;
  width: 150px;
  border-radius: 50%;
  background: #FFF;
  padding: 3px;
  transform: translateY(80px);
}
.card-image .card-img{
  height: 100%;
  width: 100%;
  object-fit: cover;
  border-radius: 50%;
 
}
.name{
  font-size: 18px;
  font-weight: 500;
  color: #333;
}
.description{
  font-size: 14px;
  color: #707070;
  text-align: center;
}
.button{
  border: none;
  font-size: 16px;
  color: #FFF;
  padding: 8px 16px;
  background-color: #16df16;
  border-radius: 6px;
  margin: 14px;
  cursor: pointer;
  transition: all 0.3s ease;
}
.button:hover{
  background: #3a970fbb;
}
.swiper-navBtn{
  color: #6E93f7;
  transition: color 0.3s ease;
}
.swiper-navBtn:hover{
  color: #4070F4;
}
.swiper-navBtn::before,
.swiper-navBtn::after{
  font-size: 35px;
}
.swiper-button-next{
  right: 0;
}
.swiper-button-prev{
  left: 0;
}
.swiper-pagination-bullet{
  background-color: #6E93f7;
  opacity: 1;
}
.swiper-pagination-bullet-active{
  background-color: #4070F4;
}
@media screen and (max-width: 768px) {
  .slide-content{
    margin: 0 10px;
  }
  .swiper-navBtn{
    display: none;
  }
}
</style>

<script>
var swiper = new Swiper(".slide-content", {
    slidesPerView: 3,
    spaceBetween: 25,
    loop: true,
    centerSlide: 'true',
    fade: 'true',
    grabCursor: 'true',
    pagination: {
        el: ".swiper-pagination",
        clickable: true,
        dynamicBullets: true,
    },
    navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
    },
    breakpoints: {
        0: {
            slidesPerView: 1,
        },
        520: {
            slidesPerView: 2,
        },
        950: {
            slidesPerView: 3,
        },
    },
});

var swiper = new Swiper(".swiper-container", {
            spaceBetween: 30,
            effect: "fade",
            loop: true,
            autoplay: {
                delay: 8500,
                disableOnInteraction: false,
            }

        });
</script>




{% endblock %}

      
  

templates/alojamiento/tipos_alojamiento_detalle.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="bg-light mt-3 text-center pb-4 bg-registration">
                <div>
                    <h1 class="font-weight-bolder text-uppercase text-center text-light py-3">
                        Habitaciones de tipo {{tipos_alojamiento.tipo}}
                    </h1>
                </div>
                <span class="text-light">
                    Están disponibles: {{habitaciones.count}}
                </span>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <!-- Tarjetas -->
        <!-- Tarjetas -->
<div class="col-lg-12 ">
    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for habitacion in habitaciones %}
        <div class="col py-2">
            <div class="card h-100">
                <div class="text-center">
                    <h5 class="mt-2 text-center font-weight-bolder bg-success text-light ml-2 mr-2">
                        $ {{tipos_alojamiento.precio}} <br />
                        Por Noche
                    </h5>
                 
                </div>
                
                <img src="{{tipos_alojamiento.imagen_1.url}}" class="card-img-top px-2" alt="..." />
                <div class="card-body">
                    <div>
                        <div class="d-flex justify-content-between small">
                            <div class="d-flex align-items-center"><i class="fa-solid fa-tags mr-2"></i>#Habt:</div>
                            <div class="">
                                {{ habitacion.numero_habitacion }}
                            </div>
                        </div>
                        <div class="small d-flex justify-content-between mt-2">
                            <div><i class="fa-solid fa-users mr-2" style="color: #af7018;"></i>Capacidad:</div>
                            <div>
                                {{tipos_alojamiento.capacidad}}
                            </div>
                        </div>
                        <div class="small d-flex justify-content-between mt-1">
                            <div><i class="fa-solid fa-bed mr-2" style="color: #0676bc;"></i>Camas:</div>
                            <div>
                                {{tipos_alojamiento.numero_camas}}
                            </div>
                        </div>
                        <div class="small d-flex justify-content-between mt-1">
                            <div><i class="fa-regular fa-square-check mr-2" style="color: #1cba43;"></i> Estado:</div>
                            <div>
                                {{habitacion.disponibles}} <i class="fa-solid fa-circle" style="color: #1bc537;"></i>
                            </div>
                        </div>
                        <input type="hidden" class="habitacion_id_{{habitacion.id}}" value="{{habitacion.id}}" id="habitacion_id"> 
                        <input type="hidden" class="num_habitacion_{{habitacion.id}}" value="{{habitacion.numero_habitacion}}" id="num_habitacion">
                        <a href="{% url 'reservacion:mi-reserva' %}?habitacion_id={{ habitacion.id }}&num_habitacion={{ habitacion.numero_habitacion }}" class="mt-2 btn btn-primary btn-sm btn-lg btn-block add-to-selection">
                            <i class="fa-solid fa-calendar-days mr-2" style="color: #1a5dd1;"></i> Reservar
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        
        <input type="hidden" value="{{alojamiento.id}}" id="id"> 
        <input type="hidden" value="{{alojamiento.nombre}}" id="nombre"> 
        <input type="hidden" value="{{tipos_alojamiento.tipo}}" id="habitacion_nombre"> 
        <input type="hidden" value="{{tipos_alojamiento.precio}}" id="habitacion_precio"> 
        <input type="hidden" value="{{tipos_alojamiento.numero_camas}}" id="numero_camas"> 
        <input type="hidden" value="{{tipos_alojamiento.id}}" id="habitacion_tipo"> 
        <input type="hidden" value="{{fecha_ingreso}}" id="fecha_ingreso"> 
        <input type="hidden" value="{{fecha_salida}}" id="fecha_salida"> 
        <input type="hidden" value="{{num_adultos}}" id="num_adultos"> 
        <input type="hidden" value="{{num_ninos}}" id="num_ninos"> 
    </div>
</div>

      
    </div>
    
</div>
<!-- Espacio rojo -->
        
{% endblock %}